# Generated by Django 3.1.7 on 2021-06-11 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoices',
            name='details',
            field=models.JSONField(),
        ),
    ]
