# Generated by Django 3.1.7 on 2021-06-13 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210611_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoices',
            name='details',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='invoices',
            name='invoice_id',
            field=models.IntegerField(unique=True),
        ),
    ]
